server:
  host: 0.0.0.0  # 监听所有网络接口，允许外部连接
  port: 8888
  max_connections: 100
  buffer_size: 4096
  heartbeat_interval: 30
  connection_timeout: 300
database:
  path: server/data/chatroom.db
  backup_enabled: true
  backup_interval: 3600
  backup_count: 5
  auto_vacuum: true
file_storage:
  path: server/data/files
  max_file_size: 104857600
  allowed_extensions:
  - .txt
  - .doc
  - .docx
  - .pdf
  - .jpg
  - .jpeg
  - .png
  - .gif
  - .mp3
  - .mp4
  - .avi
  - .zip
  - .rar
  - .py
  - .js
  - .html
  - .css
  - .md
  chunk_size: 8192
  auto_cleanup: true
  cleanup_interval: 86400
ai:
  enabled: true
  api_key: ad4315e0c7de4827ac702cef18b27d65.vr2kSgU9oQ3JkJrs
  model: glm-4-flash
  max_tokens: 1024
  temperature: 0.7
  top_p: 0.9
  max_context_length: 10
  context_timeout: 3600
  enable_group_chat: true
  enable_private_chat: true
  auto_reply: true
  trigger_keywords:
  - ai
  - 人工智能
  - 助手
  - 机器人
  - 智能
  - 问答
  require_at_mention: true
  available_models:
  - glm-4-flash
  - glm-4
  - glm-4-plus
  - glm-4-air
  - glm-4-airx
  - glm-4-long
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file_enabled: true
  file_path: logs/server/server.log
  file_max_size: 10485760
  file_backup_count: 5
  console_enabled: true
  categories:
    database:
      enabled: true
      level: DEBUG
      file_path: logs/server/database.log
    ai:
      enabled: true
      level: INFO
      file_path: logs/server/ai.log
    security:
      enabled: true
      level: WARNING
      file_path: logs/server/security.log
    performance:
      enabled: true
      level: INFO
      file_path: logs/server/performance.log
    network:
      enabled: true
      level: INFO
      file_path: logs/server/network.log
  retention:
    days: 30
    max_size_gb: 1.0
  sanitization:
    enabled: true
    patterns:
    - password
    - api_key
    - token
    - secret
    - auth
security:
  password_min_length: 6
  password_hash_rounds: 12
  session_timeout: 86400
  max_login_attempts: 5
  login_cooldown: 300
  enable_rate_limiting: true
  rate_limit_requests: 100
  rate_limit_window: 60
chat:
  default_public_chat: public
  max_message_length: 2048
  message_history_limit: 1000
  auto_create_public_chat: true
  allow_private_chat: true
  max_chat_members: 100
performance:
  enable_compression: true
  compression_level: 6
  enable_caching: true
  cache_size: 1000
  cache_ttl: 300
  worker_threads: 4
